<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>OctoMesh System communication contruction kit model</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Meshmakers.Octo.ConstructionKit.Models.System.Communication</PackageId>
        <AssemblyName>Meshmakers.Octo.ConstructionKit.Models.System.Communication</AssemblyName>
        <RootNamespace>Meshmakers.Octo.ConstructionKit.Models.System.Communication</RootNamespace>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
        <OctoPublishCkModel Condition="'$(TargetFramework)' == 'net9.0'">true</OctoPublishCkModel>
        <OctoGenerateCkDocumentation Condition="'$(TargetFramework)' == 'net9.0'">true</OctoGenerateCkDocumentation>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Meshmakers.Octo.Runtime.Contracts" Version="$(OctoVersion)" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.SourceGeneration" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Version="$(OctoVersion)" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.MsBuildTasks" Version="$(OctoVersion)" PrivateAssets="all" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.Models.System" Version="$(OctoVersion)" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath />
            <Link>LICENSE</Link>
        </None>
        <None Remove="ConstructionKit\types\sendConfiguration.yaml" />
    </ItemGroup>

    <ItemGroup>
        <ConstructionKitFolder Visible="false" Include="$(MSBuildProjectDirectory)\ConstructionKit"/>
    </ItemGroup>
</Project>
