<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>OctoMesh System communication contruction kit model</Description>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Meshmakers.Octo.ConstructionKit.Models.System.Communication</PackageId>
        <AssemblyName>Meshmakers.Octo.ConstructionKit.Models.System.Communication</AssemblyName>
        <RootNamespace>Meshmakers.Octo.ConstructionKit.Models.System.Communication</RootNamespace>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
        <OctoCompileCkModel Condition="'$(Configuration)'=='Release'">false</OctoCompileCkModel>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)'!='DebugL'">
        <PackageReference Include="Meshmakers.Octo.Runtime.Contracts" Version="3.0.30" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.SourceGeneration" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Version="3.0.30" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.MsBuildTasks" Version="3.0.30" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)'=='DebugL'">
        <PackageReference Include="Meshmakers.Octo.Runtime.Contracts" Version="999.0.0" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.SourceGeneration" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Version="999.0.0" />
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.MsBuildTasks" Version="999.0.0" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\assets\meshmakers64.png">
            <Pack>True</Pack>
            <PackagePath />
            <Link>meshmakers64.png</Link>
        </None>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath />
            <Link>LICENSE</Link>
        </None>
    </ItemGroup>
</Project>
