$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
enums:
- enumId: ConfigurationState
  values:
  - key: 0
    name: Unconfigured
  - key: 1
    name: Pending    
  - key: 2
    name: Configured
  - key: 3
    name: Error
    