$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
enums:
- enumId: DeploymentState
  useFlags: false
  values:
  - key: 0
    name: Created
  - key: 1
    name: Pending
  - key: 2
    name: Deployed
  - key: 3
    name: DeploymentError
  - key: 4
    name: ConfigurationError            