<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Meshmakers.Octo.Backend.CommunicationControllerServices.Resources</RootNamespace>
        <AssemblyName>Meshmakers.Octo.Backend.CommunicationControllerServices.Resources</AssemblyName>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

</Project>
