<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Meshmakers.Octo.Backend.CommunicationControllerServices.Resources</RootNamespace>
        <AssemblyName>Meshmakers.Octo.Backend.CommunicationControllerServices.Resources</AssemblyName>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="CommunicationControllerTexts.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>CommunicationControllerTexts.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="CommunicationControllerTexts.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CommunicationControllerTexts.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
