$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: EMailSenderConfiguration
    derivedFromCkTypeId: ${System}/Configuration
    isFinal: true
    attributes:
      - id: ${this}/Host
        name: Host
      - id: ${this}/Port
        name: Port
      - id: ${this}/SenderEmail
        name: SenderEmail
        isOptional: true
      - id: ${this}/Username
        name: Username
      - id: ${this}/Password
        name: Password  
      - id: ${this}/IsSslEnabled
        name: IsSslEnabled