$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: EnergyCommunityConfiguration
    derivedFromCkTypeId: ${this}/EdaConfiguration
    description: "Configuration for an energy community"
    attributes:
      - id: ${System}/Name
        name: Name
        isOptional: true
      - id: ${this}/EnergyCommunityId
        name: EnergyCommunityId
      - id: ${this}/HeaderLogo
        name: HeaderLogo
        isOptional: true
      - id: ${this}/FooterLogo
        name: FooterLogo
        isOptional: true
      - id: ${this}/UiThemeColors
        name: Colors
        isOptional: true
      - id: ${this}/AppTitle
        name: AppTitle
        isOptional: true
      - id: ${this}/AppHeading
        name: AppHeading
        isOptional: true
      - id: ${this}/BillingReportName
        name: BillingReportName
        isOptional: true
      - id: ${this}/HeaderGradientStart
        name: HeaderGradientStart
        isOptional: true
      - id: ${this}/HeaderGradientEnd
        name: HeaderGradientEnd
        isOptional: true
      - id: ${this}/FooterGradientStart
        name: FooterGradientStart
        isOptional: true
      - id: ${this}/FooterGradientEnd
        name: FooterGradientEnd
        isOptional: true
      - id: ${this}/BackgroundColor
        name: BackgroundColor
        isOptional: true
      - id: ${this}/Favicon
        name: Favicon
        isOptional: true
      - id: ${this}/ConsumptionRecordRequestDelay
        name: ConsumptionRecordRequestDelay
        isOptional: false
      - id: ${this}/ConsumerPrice
        name: ConsumerPrice
        isOptional: false
      - id: ${this}/ProducerPrice
        name: ProducerPrice
        isOptional: false
      - id: ${this}/TaxRate
        name: TaxRate
        isOptional: false
      - id: ${this}/FarmerTaxRate
        name: FarmerTaxRate
        isOptional: false
        