$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: Pipeline
    derivedFromCkTypeId: ${this}/DeployableEntity
    isAbstract: true
    attributes:
      - id: ${System}/Enabled
        name: Enabled 
      - id: ${this}/PipelineDefinition
        name: PipelineDefinition
    associations:
      - id: ${System}/ParentChild
        targetCkTypeId: ${this}/DataPipeline
      - id: ${this}/Executes
        targetCkTypeId: ${this}/Adapter
      - id: ${this}/Uses
        targetCkTypeId: ${System}/Configuration        
  - typeId: EdgePipeline
    derivedFromCkTypeId: ${this}/Pipeline
  - typeId: MeshPipeline
    derivedFromCkTypeId: ${this}/Pipeline
    associations:
    - id: ${this}/Triggers
      targetCkTypeId: ${this}/DataPipelineTrigger