$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: Pipeline
    derivedFromCkTypeId: ${this}/DeployableEntity
    attributes:
      - id: ${System}/Enabled
        name: Enabled
        isOptional: true
      - id: ${this}/PipelineDefinition
        name: PipelineDefinition
    associations:
      - id: ${System}/ParentChild
        targetCkTypeId: ${this}/DataFlow
      - id: ${this}/Executes
        targetCkTypeId: ${this}/Adapter
      - id: ${this}/Uses
        targetCkTypeId: ${System}/Configuration
      - id: ${this}/SendsDataTo
        targetCkTypeId: ${this}/Pipeline
