$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: SapConfiguration
    derivedFromCkTypeId: System/Configuration
    isFinal: true
    description: 'The SAP configuration type is used to configure the connection to an SAP system.'
    attributes:
      - id: ${thisModel}/Host
        name: AppServerHost
      - id: ${thisModel}/SystemNumber
        name: SystemNumber
      - id: ${thisModel}/SystemId
        name: SystemId       
        isOptional: true
      - id: ${thisModel}/Username
        name: User
      - id: ${thisModel}/Password
        name: Password
      - id: ${thisModel}/SapClient
        name: Client
      - id: ${thisModel}/SapLanguage
        name: Language
      - id: ${thisModel}/SapTrace
        name: Trace
      - id: ${thisModel}/SapGatewayHost
        name: GatewayHost
        isOptional: true
      - id: ${thisModel}/SapGatewayService
        name: GatewayService
        isOptional: true
      - id: ${thisModel}/SapProgramId
        name: ProgramId
        isOptional: true
      - id: ${thisModel}/SapRegistrationCount
        name: RegistrationCount
        isOptional: true
          
