$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: SapConfiguration
    derivedFromCkTypeId: ${System}/Configuration
    isFinal: true
    description: 'The SAP configuration type is used to configure the connection to an SAP system.'
    attributes:
      - id: ${this}/Host
        name: AppServerHost
      - id: ${this}/SystemNumber
        name: SystemNumber
      - id: ${this}/SystemId
        name: SystemId       
        isOptional: true
      - id: ${this}/Username
        name: User
      - id: ${this}/Password
        name: Password
      - id: ${this}/SapClient
        name: Client
      - id: ${this}/SapLanguage
        name: Language
      - id: ${this}/SapTrace
        name: Trace
      - id: ${this}/SapGatewayHost
        name: GatewayHost
        isOptional: true
      - id: ${this}/SapGatewayService
        name: GatewayService
        isOptional: true
      - id: ${this}/SapProgramId
        name: ProgramId
        isOptional: true
      - id: ${this}/SapRegistrationCount
        name: RegistrationCount
        isOptional: true
          
