<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <AssemblyName>Meshmakers.Octo.Backend.DeviceManagementServices</AssemblyName>
        <Description>Manages Plugs and Sockets for data ingress and egress of an Octo Mesh instance</Description>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <RootNamespace>Meshmakers.Octo.Backend.DeviceManagementServices</RootNamespace>
        <StartupObject />
        <UserSecretsId>04bcde24-0d21-4346-8459-3bca58abec32</UserSecretsId>
        <Version>1.0.0</Version>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>../../bin/Debug/DeviceManagementServices/</OutputPath>
        <DocumentationFile>../../bin/Debug/DeviceManagementServices/Meshmakers.Octo.Backend.DeviceManagementServices.xml</DocumentationFile>
        <NoWarn>1701;1702;CS8002</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>../../bin/Release/DeviceManagementServices/</OutputPath>
        <DocumentationFile>../../bin/Release/AssetRepositoryServices/Meshmakers.Octo.Backend.DeviceManagementServices.xml</DocumentationFile>
        <NoWarn>1701;1702;CS8002</NoWarn>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.5" />
        <PackageReference Include="NLog.Web.AspNetCore" Version="5.2.3" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DeviceManagementServices.Resources\DeviceManagementServices.Resources.csproj" />
      <ProjectReference Include="..\octo-common-services\src\Swagger\Swagger.csproj" />
      <ProjectReference Include="..\octo-core\src\Common\Communication.Contracts\Communication.Contracts.csproj" />
      <ProjectReference Include="..\octo-core\src\Common\Communication.Plugs.Contracts\Communication.Plugs.Contracts.csproj" />
      <ProjectReference Include="..\octo-core\src\SystematizedData\Persistence\Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="nlog.config" />
      <None Include="nlog.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
